[package]
name = "fat32"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
log = "0.4"
nix = { version = "0.29", features = ["uio", "fs"] }
parking_lot = "0.12.3"
thiserror = "1.0.61"
